version: "3"
services:
        nginx:
                container_name: nginx
                image: nginx
                ports:
                        - 8000:80
                volumes:
                        - ./server:/var/www
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - php
        php:
                container_name: php
                build: ./php
                ports:
                        - 8080:8080
                volumes:
                        - ./server:/var/www
                depends_on:
                        - db
        db:
                image: mysql:5.7
                restart: always
                container_name: db-host
                environment:
                        MYSQL_DATABASE: community
                        MYSQL_USER: community
                        MYSQL_PASSWORD: Com%44.ww
                        MYSQL_ROOT_PASSWORD: Com%44.ww
                        TZ: "Asia/Tokyo"
                command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
                ports:
                        - 3306:3306
